version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      laravel:
        patterns:
          - "laravel/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
